name: Update documentation assets (master only)
on:
  push:
    branches: [master]

jobs:
  generate-docs-assets:
    name: Update documentation assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: heinrichreimer/github-changelog-generator-action@6f5b9494dd265d6fb7243a10c53dc0169c55f247 # renovate: tag=v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
      - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9.1.3
        with:
          add: |
            CHANGELOG.md
            README.md
          default_author: github_actions
          message: "Update documentation assets"
